name: Gating
on:
  push:
    branches: [ master, stabilization* ]
  pull_request:
    branches: [ master ]
jobs:
  validate-ubuntu:
    name: Build, Test on Ubuntu 20.04
    runs-on: ubuntu-20.04
    steps:
      - name: Install Deps
        uses: mstksg/get-package@master
        with:
          apt-get: cmake ninja-build libopenscap8 libxml2-utils expat xsltproc python3-jinja2 python3-yaml ansible-lint python3-github
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: ./build_product chromium fedora firefox fuse6 rhcos4 rhel7 rhel8 rhel9 rhosp10 rhosp13 sle12 sle15 ubuntu2004
      - name: Test
        run: ctest -j2 --output-on-failure -E unique-stigids
        working-directory: ./build

  validate-fedora:
    name: Build, Test on Fedora 33 (Container)
    runs-on: ubuntu-latest
    container:
      image: fedora:33
    steps:
      - name: Install Deps
        run: dnf install -y cmake ninja-build openscap-utils python3-pyyaml python3-jinja2 bats python3-pytest ansible python3-pip
      - name: Install deps python
        run: pip install ruamel.yaml yamlpath
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Build
      #   run: ./build_product chromium fedora firefox fuse6 rhcos4 rhel7 rhel8 rhel9 rhosp10 rhosp13 sle12 sle15 ubuntu2004 ocp4
      - name: Configure cmake (command generated by bash -x ./build_product)
        run: |-
          cmake .. -DCMAKE_BUILD_TYPE=Release \
                  -G Ninja \
                  -DSSG_TARGET_OVAL_MAJOR_VERSION:STRING=5 \
                  -DSSG_TARGET_OVAL_MINOR_VERSION:STRING=11 \
                  -DSSG_PRODUCT_DEFAULT=OFF \
                  -DSSG_PRODUCT_CHROMIUM=ON \
                  -DSSG_PRODUCT_FEDORA=ON \
                  -DSSG_PRODUCT_FIREFOX=ON \
                  -DSSG_PRODUCT_FUSE6=ON \
                  -DSSG_PRODUCT_RHCOS4=ON \
                  -DSSG_PRODUCT_RHEL7=ON \
                  -DSSG_PRODUCT_RHEL8=ON \
                  -DSSG_PRODUCT_RHEL9=ON \
                  -DSSG_PRODUCT_RHOSP10=ON \
                  -DSSG_PRODUCT_RHOSP13=ON \
                  -DSSG_PRODUCT_SLE12=ON \
                  -DSSG_PRODUCT_SLE15=ON \
                  -DSSG_PRODUCT_UBUNTU2004=ON \
                  -DSSG_CENTOS_DERIVATIVES_ENABLED:BOOL=OFF \
                  -DSSG_SCIENTIFIC_LINUX_DERIVATIVES_ENABLED:BOOL=OFF \
                  -DSSG_ANSIBLE_PLAYBOOKS_PER_RULE_ENABLED=ON # Enable playbooks per rule and sanity tests for ansible
        working-directory: ./build
      - name: Build
        run: ninja -j4
        working-directory: ./build
      - name: Test
        run: ctest -j2 --output-on-failure -E unique-stigids
        working-directory: ./build
