name: CTF
on:
  pull_request:
    branches: [ master ]
jobs:
  content-test-filtering:
    name: Content Test Filtering on Ubuntu Latest
    runs-on: ubuntu-latest
    steps:
      - name: Install Deps
        uses: mstksg/get-package@master
        with:
          apt-get: git python3-jinja2 python3-yaml python3-deepdiff python3-git python3-github python3-requests xmldiff
      - name: Checkout (CTF)
        uses: actions/checkout@v2
        with:
          repository: mildas/content-test-filtering
          path: ctf
      - name: Process (see the output for recommended tests)
        run: python3 ./ctf/content_test_filtering.py pr --remote_repo https://github.com/ggbecker/content --verbose --rule --output json ${{ github.event.pull_request.number }} > ctf.json
      - name: Test if there are no content changes
        run: echo "::set-output name=CTF_OUTPUT_SIZE::$(stat --printf="%s" ctf.json)"
        id: ctf
      - name: Exit if there are no changes detected
        if: ${{ steps.ctf.outputs.CTF_OUTPUT_SIZE == '0' }}
        run: exit 1
      - name: Upload CTF output
        uses: actions/upload-artifact@v2
        with:
          name: ctf.json
          path: ctf.json
